#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EngRule {
    pub left: &'static str,
    pub mat: &'static str,
    pub right: &'static str,
    pub out: &'static str,
}

#[rustfmt::skip]
pub const RULES: [&[EngRule]; 27] = [

    &PUNCT_RULES,
    &A_RULES,
    &B_RULES,
    &C_RULES,
    &D_RULES,
    &E_RULES,
    &F_RULES,
    &G_RULES,
    &H_RULES,
    &I_RULES,
    &J_RULES,
    &K_RULES,
    &L_RULES,
    &M_RULES,
    &N_RULES,
    &O_RULES,
    &P_RULES,
    &Q_RULES,
    &R_RULES,
    &S_RULES,
    &T_RULES,
    &U_RULES,
    &V_RULES,
    &W_RULES,
    &X_RULES,
    &Y_RULES,
    &Z_RULES,
];

#[rustfmt::skip]
pub const PUNCT_RULES: [EngRule; 10] = [
    EngRule { left: "", mat: " ", right: "", out: " " },
    EngRule { left: "", mat: "-", right: "", out: "" },
    EngRule { left: ".", mat: "'S", right: "", out: "z" },
    EngRule { left: "#:.E", mat: "'S", right: "", out: "z" },
    EngRule { left: "#", mat: "'S", right: "", out: "z" },
    EngRule { left: "", mat: "'", right: "", out: "" },
    EngRule { left: "", mat: ",", right: "", out: " " },
    EngRule { left: "", mat: ".", right: "", out: " " },
    EngRule { left: "", mat: "?", right: "", out: " " },
    EngRule { left: "", mat: "!", right: "", out: " " },
];

#[rustfmt::skip]
pub const A_RULES: [EngRule; 33] = [
    EngRule { left: "", mat: "A", right: " ", out: "AX" },
    EngRule { left: " ", mat: "ARE", right: " ", out: "AAr" },
    EngRule { left: " ", mat: "AR", right: "O", out: "AXr" },
    EngRule { left: "", mat: "AR", right: "#", out: "EHr" },
    EngRule { left: "^", mat: "AS", right: "#", out: "EYs" },
    EngRule { left: "", mat: "A", right: "WA", out: "AX" },
    EngRule { left: "", mat: "AW", right: "", out: "AO" },
    EngRule { left: " :", mat: "ANY", right: "", out: "EHnIY" },
    EngRule { left: "", mat: "A", right: "^+#", out: "EY" },
    EngRule { left: "#:", mat: "ALLY", right: "", out: "AXlIY" },
    EngRule { left: " ", mat: "AL", right: "#", out: "AXl" },
    EngRule { left: "", mat: "AGAIN", right: "", out: "AXgEHn" },
    EngRule { left: "#:", mat: "AG", right: "E", out: "IHj" },
    EngRule { left: "", mat: "A", right: "^+:#", out: "AE" },
    EngRule { left: " :", mat: "A", right: "^+ ", out: "EY" },
    EngRule { left: "", mat: "A", right: "^%", out: "EY" },
    EngRule { left: " ", mat: "ARR", right: "", out: "AXr" },
    EngRule { left: "", mat: "ARR", right: "", out: "AEr" },
    EngRule { left: " :", mat: "AR", right: " ", out: "AAr" },
    EngRule { left: "", mat: "AR", right: " ", out: "ER" },
    EngRule { left: "", mat: "AR", right: "", out: "AAr" },
    EngRule { left: "", mat: "AIR", right: "", out: "EHr" },
    EngRule { left: "", mat: "AI", right: "", out: "EY" },
    EngRule { left: "", mat: "AY", right: "", out: "EY" },
    EngRule { left: "", mat: "AU", right: "", out: "AO" },
    EngRule { left: "#:", mat: "AL", right: " ", out: "AXl" },
    EngRule { left: "#:", mat: "ALS", right: " ", out: "AXlz" },
    EngRule { left: "", mat: "ALK", right: "", out: "AOk" },
    EngRule { left: "", mat: "AL", right: "^", out: "AOl" },
    EngRule { left: " :", mat: "ABLE", right: "", out: "EYbAXl" },
    EngRule { left: "", mat: "ABLE", right: "", out: "AXbAXl" },
    EngRule { left: "", mat: "ANG", right: "+", out: "EYnj" },
    EngRule { left: "", mat: "A", right: "", out: "AE" },
];

#[rustfmt::skip]
pub const B_RULES: [EngRule; 6] = [
    EngRule { left: " ", mat: "BE", right: "^#", out: "bIH" },
    EngRule { left: "", mat: "BEING", right: "", out: "bIYIHNG" },
    EngRule { left: " ", mat: "BOTH", right: " ", out: "bOWTH" },
    EngRule { left: " ", mat: "BUS", right: "#", out: "bIHz" },
    EngRule { left: "", mat: "BUIL", right: "", out: "bIHl" },
    EngRule { left: "", mat: "B", right: "", out: "b" },
];

#[rustfmt::skip]
pub const C_RULES: [EngRule; 11] = [
    EngRule { left: " ", mat: "CH", right: "^", out: "k" },
    EngRule { left: "^E", mat: "CH", right: "", out: "k" },
    EngRule { left: "", mat: "CH", right: "", out: "CH" },
    EngRule { left: " S", mat: "CI", right: "#", out: "sAY" },
    EngRule { left: "", mat: "CI", right: "A", out: "SH" },
    EngRule { left: "", mat: "CI", right: "O", out: "SH" },
    EngRule { left: "", mat: "CI", right: "EN", out: "SH" },
    EngRule { left: "", mat: "C", right: "+", out: "s" },
    EngRule { left: "", mat: "CK", right: "", out: "k" },
    EngRule { left: "", mat: "COM", right: "%", out: "kAHm" },
    EngRule { left: "", mat: "C", right: "", out: "k" },
];

#[rustfmt::skip]
pub const D_RULES: [EngRule; 10] = [
    EngRule { left: "#:", mat: "DED", right: " ", out: "dIHd" },
    EngRule { left: ".E", mat: "D", right: " ", out: "d" },
    EngRule { left: "#:^E", mat: "D", right: " ", out: "t" },
    EngRule { left: " ", mat: "DE", right: "^#", out: "dIH" },
    EngRule { left: " ", mat: "DO", right: " ", out: "dUW" },
    EngRule { left: " ", mat: "DOES", right: "", out: "dAHz" },
    EngRule { left: " ", mat: "DOING", right: "", out: "dUWIHNG" },
    EngRule { left: " ", mat: "DOW", right: "", out: "dAW" },
    EngRule { left: "", mat: "DU", right: "A", out: "jUW" },
    EngRule { left: "", mat: "D", right: "", out: "d" },
];

#[rustfmt::skip]
pub const E_RULES: [EngRule; 52] = [
    EngRule { left: "#:", mat: "E", right: " ", out: "" },
    EngRule { left: "':^", mat: "E", right: " ", out: "" },
    EngRule { left: " :", mat: "E", right: " ", out: "IY" },
    EngRule { left: "#", mat: "ED", right: " ", out: "d" },
    EngRule { left: "#:", mat: "E", right: "D ", out: "" },
    EngRule { left: "", mat: "EV", right: "ER", out: "EHv" },
    EngRule { left: "", mat: "E", right: "^%", out: "IY" },
    EngRule { left: "", mat: "ERI", right: "#", out: "IYrIY" },
    EngRule { left: "", mat: "ERI", right: "", out: "EHrIH" },
    EngRule { left: "#:", mat: "ER", right: "#", out: "ER" },
    EngRule { left: "", mat: "ER", right: "#", out: "EHr" },
    EngRule { left: "", mat: "ER", right: "", out: "ER" },
    EngRule { left: " ", mat: "EVEN", right: "", out: "IYvEHn" },
    EngRule { left: "#:", mat: "E", right: "W", out: "" },
    EngRule { left: "T", mat: "EW", right: "", out: "UW" },
    EngRule { left: "S", mat: "EW", right: "", out: "UW" },
    EngRule { left: "R", mat: "EW", right: "", out: "UW" },
    EngRule { left: "D", mat: "EW", right: "", out: "UW" },
    EngRule { left: "L", mat: "EW", right: "", out: "UW" },
    EngRule { left: "Z", mat: "EW", right: "", out: "UW" },
    EngRule { left: "N", mat: "EW", right: "", out: "UW" },
    EngRule { left: "J", mat: "EW", right: "", out: "UW" },
    EngRule { left: "TH", mat: "EW", right: "", out: "UW" },
    EngRule { left: "CH", mat: "EW", right: "", out: "UW" },
    EngRule { left: "SH", mat: "EW", right: "", out: "UW" },
    EngRule { left: "", mat: "EW", right: "", out: "yUW" },
    EngRule { left: "", mat: "E", right: "O", out: "IY" },
    EngRule { left: "#:S", mat: "ES", right: " ", out: "IHz" },
    EngRule { left: "#:C", mat: "ES", right: " ", out: "IHz" },
    EngRule { left: "#:G", mat: "ES", right: " ", out: "IHz" },
    EngRule { left: "#:Z", mat: "ES", right: " ", out: "IHz" },
    EngRule { left: "#:X", mat: "ES", right: " ", out: "IHz" },
    EngRule { left: "#:J", mat: "ES", right: " ", out: "IHz" },
    EngRule { left: "#:CH", mat: "ES", right: " ", out: "IHz" },
    EngRule { left: "#:SH", mat: "ES", right: " ", out: "IHz" },
    EngRule { left: "#:", mat: "E", right: "S ", out: "" },
    EngRule { left: "#:", mat: "ELY", right: " ", out: "lIY" },
    EngRule { left: "#:", mat: "EMENT", right: "", out: "mEHnt" },
    EngRule { left: "", mat: "EFUL", right: "", out: "fUHl" },
    EngRule { left: "", mat: "EE", right: "", out: "IY" },
    EngRule { left: "", mat: "EARN", right: "", out: "ERn" },
    EngRule { left: " ", mat: "EAR", right: "^", out: "ER" },
    EngRule { left: "", mat: "EAD", right: "", out: "EHd" },
    EngRule { left: "#:", mat: "EA", right: " ", out: "IYAX" },
    EngRule { left: "", mat: "EA", right: "SU", out: "EH" },
    EngRule { left: "", mat: "EA", right: "", out: "IY" },
    EngRule { left: "", mat: "EIGH", right: "", out: "EY" },
    EngRule { left: "", mat: "EI", right: "", out: "IY" },
    EngRule { left: " ", mat: "EYE", right: "", out: "AY" },
    EngRule { left: "", mat: "EY", right: "", out: "IY" },
    EngRule { left: "", mat: "EU", right: "", out: "yUW" },
    EngRule { left: "", mat: "E", right: "", out: "EH" },
];

#[rustfmt::skip]
pub const F_RULES: [EngRule; 2] = [
    EngRule { left: "", mat: "FUL", right: "", out: "fUHl" },
    EngRule { left: "", mat: "F", right: "", out: "f" },
];

#[rustfmt::skip]
pub const G_RULES: [EngRule; 10] = [
    EngRule { left: "", mat: "GIV", right: "", out: "gIHv" },
    EngRule { left: " ", mat: "G", right: "I^", out: "g" },
    EngRule { left: "", mat: "GE", right: "T", out: "gEH" },
    EngRule { left: "SU", mat: "GGES", right: "", out: "gjEHs" },
    EngRule { left: "", mat: "GG", right: "", out: "g" },
    EngRule { left: " B#", mat: "G", right: "", out: "g" },
    EngRule { left: "", mat: "G", right: "+", out: "j" },
    EngRule { left: "", mat: "GREAT", right: "", out: "grEYt" },
    EngRule { left: "#", mat: "GH", right: "", out: "" },
    EngRule { left: "", mat: "G", right: "", out: "g" },
];

#[rustfmt::skip]
pub const H_RULES: [EngRule; 6] = [
    EngRule { left: " ", mat: "HAV", right: "", out: "hAEv" },
    EngRule { left: " ", mat: "HERE", right: "", out: "hIYr" },
    EngRule { left: " ", mat: "HOUR", right: "", out: "AWER" },
    EngRule { left: "", mat: "HOW", right: "", out: "hAW" },
    EngRule { left: "", mat: "H", right: "#", out: "h" },
    EngRule { left: "", mat: "H", right: "", out: "" },
];

#[rustfmt::skip]
pub const I_RULES: [EngRule; 28] = [
    EngRule { left: " ", mat: "IN", right: "", out: "IHn" },
    EngRule { left: " ", mat: "I", right: " ", out: "AY" },
    EngRule { left: "", mat: "IN", right: "D", out: "AYn" },
    EngRule { left: "", mat: "IER", right: "", out: "IYER" },
    EngRule { left: "#:R", mat: "IED", right: "", out: "IYd" },
    EngRule { left: "", mat: "IED", right: " ", out: "AYd" },
    EngRule { left: "", mat: "IEN", right: "", out: "IYEHn" },
    EngRule { left: "", mat: "IE", right: "T", out: "AYEH" },
    EngRule { left: " :", mat: "I", right: "%", out: "AY" },
    EngRule { left: "", mat: "I", right: "%", out: "IY" },
    EngRule { left: "", mat: "IE", right: "", out: "IY" },
    EngRule { left: "", mat: "I", right: "^+:#", out: "IH" },
    EngRule { left: "", mat: "IR", right: "#", out: "AYr" },
    EngRule { left: "", mat: "IZ", right: "%", out: "AYz" },
    EngRule { left: "", mat: "IS", right: "%", out: "AYz" },
    EngRule { left: "", mat: "I", right: "D%", out: "AY" },
    EngRule { left: "+^", mat: "I", right: "^+", out: "IH" },
    EngRule { left: "", mat: "I", right: "T%", out: "AY" },
    EngRule { left: "#:^", mat: "I", right: "^+", out: "IH" },
    EngRule { left: "", mat: "I", right: "^+", out: "AY" },
    EngRule { left: "", mat: "IR", right: "", out: "ER" },
    EngRule { left: "", mat: "IGH", right: "", out: "AY" },
    EngRule { left: "", mat: "ILD", right: "", out: "AYld" },
    EngRule { left: "", mat: "IGN", right: " ", out: "AYn" },
    EngRule { left: "", mat: "IGN", right: "^", out: "AYn" },
    EngRule { left: "", mat: "IGN", right: "%", out: "AYn" },
    EngRule { left: "", mat: "IQUE", right: "", out: "IYk" },
    EngRule { left: "", mat: "I", right: "", out: "IH" },
];

#[rustfmt::skip]
pub const J_RULES: [EngRule; 1] = [
    EngRule { left: "", mat: "J", right: "", out: "j" },
];

#[rustfmt::skip]
pub const K_RULES: [EngRule; 2] = [
    EngRule { left: " ", mat: "K", right: "N", out: "" },
    EngRule { left: "", mat: "K", right: "", out: "k" },
];

#[rustfmt::skip]
pub const L_RULES: [EngRule; 5] = [
    EngRule { left: "", mat: "LO", right: "C#", out: "lOW" },
    EngRule { left: "L", mat: "L", right: "", out: "" },
    EngRule { left: "#:^", mat: "L", right: "%", out: "AXl" },
    EngRule { left: "", mat: "LEAD", right: "", out: "lIYd" },
    EngRule { left: "", mat: "L", right: "", out: "l" },
];

#[rustfmt::skip]
pub const M_RULES: [EngRule; 2] = [
    EngRule { left: "", mat: "MOV", right: "", out: "mUWv" },
    EngRule { left: "", mat: "M", right: "", out: "m" },
];

#[rustfmt::skip]
pub const N_RULES: [EngRule; 8] = [
    EngRule { left: "E", mat: "NG", right: "+", out: "nj" },
    EngRule { left: "", mat: "NG", right: "R", out: "NGg" },
    EngRule { left: "", mat: "NG", right: "#", out: "NGg" },
    EngRule { left: "", mat: "NGL", right: "%", out: "NGgAXl" },
    EngRule { left: "", mat: "NG", right: "", out: "NG" },
    EngRule { left: "", mat: "NK", right: "", out: "NGk" },
    EngRule { left: " ", mat: "NOW", right: " ", out: "nAW" },
    EngRule { left: "", mat: "N", right: "", out: "n" },
];

#[rustfmt::skip]
pub const O_RULES: [EngRule; 48] = [
    EngRule { left: "", mat: "OF", right: " ", out: "AXv" },
    EngRule { left: "", mat: "OROUGH", right: "", out: "EROW" },
    EngRule { left: "#:", mat: "OR", right: " ", out: "ER" },
    EngRule { left: "#:", mat: "ORS", right: " ", out: "ERz" },
    EngRule { left: "", mat: "OR", right: "", out: "AOr" },
    EngRule { left: " ", mat: "ONE", right: "", out: "wAHn" },
    EngRule { left: "", mat: "OW", right: "", out: "OW" },
    EngRule { left: " ", mat: "OVER", right: "", out: "OWvER" },
    EngRule { left: "", mat: "OV", right: "", out: "AHv" },
    EngRule { left: "", mat: "O", right: "^%", out: "OW" },
    EngRule { left: "", mat: "O", right: "^EN", out: "OW" },
    EngRule { left: "", mat: "O", right: "^I#", out: "OW" },
    EngRule { left: "", mat: "OL", right: "D", out: "OWl" },
    EngRule { left: "", mat: "OUGHT", right: "", out: "AOt" },
    EngRule { left: "", mat: "OUGH", right: "", out: "AHf" },
    EngRule { left: " ", mat: "OU", right: "", out: "AW" },
    EngRule { left: "H", mat: "OU", right: "S#", out: "AW" },
    EngRule { left: "", mat: "OUS", right: "", out: "AXs" },
    EngRule { left: "", mat: "OUR", right: "", out: "AOr" },
    EngRule { left: "", mat: "OULD", right: "", out: "UHd" },
    EngRule { left: "^", mat: "OU", right: "^L", out: "AH" },
    EngRule { left: "", mat: "OUP", right: "", out: "UWp" },
    EngRule { left: "", mat: "OU", right: "", out: "AW" },
    EngRule { left: "", mat: "OY", right: "", out: "OY" },
    EngRule { left: "", mat: "OING", right: "", out: "OWIHNG" },
    EngRule { left: "", mat: "OI", right: "", out: "OY" },
    EngRule { left: "", mat: "OOR", right: "", out: "AOr" },
    EngRule { left: "", mat: "OOK", right: "", out: "UHk" },
    EngRule { left: "", mat: "OOD", right: "", out: "UHd" },
    EngRule { left: "", mat: "OO", right: "", out: "UW" },
    EngRule { left: "", mat: "O", right: "E", out: "OW" },
    EngRule { left: "", mat: "O", right: " ", out: "OW" },
    EngRule { left: "", mat: "OA", right: "", out: "OW" },
    EngRule { left: " ", mat: "ONLY", right: "", out: "OWnlIY" },
    EngRule { left: " ", mat: "ONCE", right: "", out: "wAHns" },
    EngRule { left: "", mat: "ON'T", right: "", out: "OWnt" },
    EngRule { left: "C", mat: "O", right: "N", out: "AA" },
    EngRule { left: "", mat: "O", right: "NG", out: "AO" },
    EngRule { left: " :^", mat: "O", right: "N", out: "AH" },
    EngRule { left: "I", mat: "ON", right: "", out: "AXn" },
    EngRule { left: "#:", mat: "ON", right: " ", out: "AXn" },
    EngRule { left: "#^", mat: "ON", right: "", out: "AXn" },
    EngRule { left: "", mat: "O", right: "ST ", out: "OW" },
    EngRule { left: "", mat: "OF", right: "^", out: "AOf" },
    EngRule { left: "", mat: "OTHER", right: "", out: "AHDHER" },
    EngRule { left: "", mat: "OSS", right: " ", out: "AOs" },
    EngRule { left: "#:^", mat: "OM", right: "", out: "AHm" },
    EngRule { left: "", mat: "O", right: "", out: "AA" },
];

#[rustfmt::skip]
pub const P_RULES: [EngRule; 5] = [
    EngRule { left: "", mat: "PH", right: "", out: "f" },
    EngRule { left: "", mat: "PEOP", right: "", out: "pIYp" },
    EngRule { left: "", mat: "POW", right: "", out: "pAW" },
    EngRule { left: "", mat: "PUT", right: " ", out: "pUHt" },
    EngRule { left: "", mat: "P", right: "", out: "p" },
];

#[rustfmt::skip]
pub const Q_RULES: [EngRule; 3] = [
    EngRule { left: "", mat: "QUAR", right: "", out: "kwAOr" },
    EngRule { left: "", mat: "QU", right: "", out: "kw" },
    EngRule { left: "", mat: "Q", right: "", out: "k" },
];

#[rustfmt::skip]
pub const R_RULES: [EngRule; 2] = [
    EngRule { left: " ", mat: "RE", right: "^#", out: "rIY" },
    EngRule { left: "", mat: "R", right: "", out: "r" },
];

#[rustfmt::skip]
pub const S_RULES: [EngRule; 23] = [
    EngRule { left: "", mat: "SH", right: "", out: "SH" },
    EngRule { left: "#", mat: "SION", right: "", out: "ZHAXn" },
    EngRule { left: "", mat: "SOME", right: "", out: "sAHm" },
    EngRule { left: "#", mat: "SUR", right: "#", out: "ZHER" },
    EngRule { left: "", mat: "SUR", right: "#", out: "SHER" },
    EngRule { left: "#", mat: "SU", right: "#", out: "ZHUW" },
    EngRule { left: "#", mat: "SSU", right: "#", out: "SHUW" },
    EngRule { left: "#", mat: "SED", right: " ", out: "zd" },
    EngRule { left: "#", mat: "S", right: "#", out: "z" },
    EngRule { left: "", mat: "SAID", right: "", out: "sEHd" },
    EngRule { left: "^", mat: "SION", right: "", out: "SHAXn" },
    EngRule { left: "", mat: "S", right: "S", out: "" },
    EngRule { left: ".", mat: "S", right: " ", out: "z" },
    EngRule { left: "#:.E", mat: "S", right: " ", out: "z" },
    EngRule { left: "#:^##", mat: "S", right: " ", out: "z" },
    EngRule { left: "#:^#", mat: "S", right: " ", out: "s" },
    EngRule { left: "U", mat: "S", right: " ", out: "s" },
    EngRule { left: " :#", mat: "S", right: " ", out: "z" },
    EngRule { left: " ", mat: "SCH", right: "", out: "sk" },
    EngRule { left: "", mat: "S", right: "C+", out: "" },
    EngRule { left: "#", mat: "SM", right: "", out: "zm" },
    EngRule { left: "#", mat: "SN", right: "'", out: "zAXn" },
    EngRule { left: "", mat: "S", right: "", out: "s" },
];

#[rustfmt::skip]
pub const T_RULES: [EngRule; 26] = [
    EngRule { left: " ", mat: "THE", right: " ", out: "DHAX" },
    EngRule { left: "", mat: "TO", right: " ", out: "tUW" },
    EngRule { left: "", mat: "THAT", right: " ", out: "DHAEt" },
    EngRule { left: " ", mat: "THIS", right: " ", out: "DHIHs" },
    EngRule { left: " ", mat: "THEY", right: "", out: "DHEY" },
    EngRule { left: " ", mat: "THERE", right: "", out: "DHEHr" },
    EngRule { left: "", mat: "THER", right: "", out: "DHER" },
    EngRule { left: "", mat: "THEIR", right: "", out: "DHEHr" },
    EngRule { left: " ", mat: "THAN", right: " ", out: "DHAEn" },
    EngRule { left: " ", mat: "THEM", right: " ", out: "DHEHm" },
    EngRule { left: "", mat: "THESE", right: " ", out: "DHIYz" },
    EngRule { left: " ", mat: "THEN", right: "", out: "DHEHn" },
    EngRule { left: "", mat: "THROUGH", right: "", out: "THrUW" },
    EngRule { left: "", mat: "THOSE", right: "", out: "DHOWz" },
    EngRule { left: "", mat: "THOUGH", right: " ", out: "DHOW" },
    EngRule { left: " ", mat: "THUS", right: "", out: "DHAHs" },
    EngRule { left: "", mat: "TH", right: "", out: "TH" },
    EngRule { left: "#:", mat: "TED", right: " ", out: "tIHd" },
    EngRule { left: "S", mat: "TI", right: "#N", out: "CH" },
    EngRule { left: "", mat: "TI", right: "O", out: "SH" },
    EngRule { left: "", mat: "TI", right: "A", out: "SH" },
    EngRule { left: "", mat: "TIEN", right: "", out: "SHAXn" },
    EngRule { left: "", mat: "TUR", right: "#", out: "CHER" },
    EngRule { left: "", mat: "TU", right: "A", out: "CHUW" },
    EngRule { left: " ", mat: "TWO", right: "", out: "tUW" },
    EngRule { left: "", mat: "T", right: "", out: "t" },
];

#[rustfmt::skip]
pub const U_RULES: [EngRule; 35] = [
    EngRule { left: " ", mat: "UN", right: "I", out: "yUWn" },
    EngRule { left: " ", mat: "UN", right: "", out: "AHn" },
    EngRule { left: " ", mat: "UPON", right: "", out: "AXpAOn" },
    EngRule { left: "T", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "S", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "R", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "D", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "L", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "Z", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "N", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "J", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "TH", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "CH", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "SH", mat: "UR", right: "#", out: "UHr" },
    EngRule { left: "", mat: "UR", right: "#", out: "yUHr" },
    EngRule { left: "", mat: "UR", right: "", out: "ER" },
    EngRule { left: "", mat: "U", right: "^ ", out: "AH" },
    EngRule { left: "", mat: "U", right: "^^", out: "AH" },
    EngRule { left: "", mat: "UY", right: "", out: "AY" },
    EngRule { left: " G", mat: "U", right: "#", out: "" },
    EngRule { left: "G", mat: "U", right: "%", out: "" },
    EngRule { left: "G", mat: "U", right: "#", out: "w" },
    EngRule { left: "#N", mat: "U", right: "", out: "yUW" },
    EngRule { left: "T", mat: "U", right: "", out: "UW" },
    EngRule { left: "S", mat: "U", right: "", out: "UW" },
    EngRule { left: "R", mat: "U", right: "", out: "UW" },
    EngRule { left: "D", mat: "U", right: "", out: "UW" },
    EngRule { left: "L", mat: "U", right: "", out: "UW" },
    EngRule { left: "Z", mat: "U", right: "", out: "UW" },
    EngRule { left: "N", mat: "U", right: "", out: "UW" },
    EngRule { left: "J", mat: "U", right: "", out: "UW" },
    EngRule { left: "TH", mat: "U", right: "", out: "UW" },
    EngRule { left: "CH", mat: "U", right: "", out: "UW" },
    EngRule { left: "SH", mat: "U", right: "", out: "UW" },
    EngRule { left: "", mat: "U", right: "", out: "yUW" },
];

#[rustfmt::skip]
pub const V_RULES: [EngRule; 2] = [
    EngRule { left: "", mat: "VIEW", right: "", out: "vyUW" },
    EngRule { left: "", mat: "V", right: "", out: "v" },
];

#[rustfmt::skip]
pub const W_RULES: [EngRule; 12] = [
    EngRule { left: " ", mat: "WERE", right: "", out: "wER" },
    EngRule { left: "", mat: "WA", right: "S", out: "wAA" },
    EngRule { left: "", mat: "WA", right: "T", out: "wAA" },
    EngRule { left: "", mat: "WHERE", right: "", out: "WHEHr" },
    EngRule { left: "", mat: "WHAT", right: "", out: "WHAAt" },
    EngRule { left: "", mat: "WHOL", right: "", out: "hOWl" },
    EngRule { left: "", mat: "WHO", right: "", out: "hUW" },
    EngRule { left: "", mat: "WH", right: "", out: "WH" },
    EngRule { left: "", mat: "WAR", right: "", out: "wAOr" },
    EngRule { left: "", mat: "WOR", right: "^", out: "wER" },
    EngRule { left: "", mat: "WR", right: "", out: "r" },
    EngRule { left: "", mat: "W", right: "", out: "w" },
];

#[rustfmt::skip]
pub const X_RULES: [EngRule; 1] = [
    EngRule { left: "", mat: "X", right: "", out: "ks" },
];

#[rustfmt::skip]
pub const Y_RULES: [EngRule; 11] = [
    EngRule { left: "", mat: "YOUNG", right: "", out: "yAHNG" },
    EngRule { left: " ", mat: "YOU", right: "", out: "yUW" },
    EngRule { left: " ", mat: "YES", right: "", out: "yEHs" },
    EngRule { left: " ", mat: "Y", right: "", out: "y" },
    EngRule { left: "#:^", mat: "Y", right: " ", out: "IY" },
    EngRule { left: "#:^", mat: "Y", right: "I", out: "IY" },
    EngRule { left: " :", mat: "Y", right: " ", out: "AY" },
    EngRule { left: " :", mat: "Y", right: "#", out: "AY" },
    EngRule { left: " :", mat: "Y", right: "^+:#", out: "IH" },
    EngRule { left: " :", mat: "Y", right: "^#", out: "AY" },
    EngRule { left: "", mat: "Y", right: "", out: "IH" },
];

#[rustfmt::skip]
pub const Z_RULES: [EngRule; 1] = [
    EngRule { left: "", mat: "Z", right: "", out: "z" },
];

#[rustfmt::skip]
pub const CSWTCH_55: [i32; 43] = [
    8, 8, 8, 8, 9, 9, 2, 5, 2, 3, 8, 8,
    9, 3, 2, 10, 8, 8, 5, 1, 7, 6, 6, 6,
    9, 9, 1, 7, 3, 3, 1, 3, 8, 8, 3, 11,
    12, 3, 3, 8, 11, 4, 4,
];
#[rustfmt::skip]
pub const CSWTCH_58: [i32; 39] = [
    1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
    0, 0, 1,
];
#[rustfmt::skip]
pub const CSWTCH_61: [i32; 37] = [
    1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
    1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
    1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
    1,
];
#[rustfmt::skip]
pub const CSWTCH_64: [i32; 33] = [
    1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
    1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
    1, 1, 0, 0, 1, 1, 1, 1, 1,
];
#[rustfmt::skip]
pub const GSCH_ASCII: [&str; 128] = [
    "nUWl ",
    "stAArt AXv hEHdER ",
    "stAArt AXv tEHkst ",
    "EHnd AXv tEHkst ",
    "EHnd AXv trAEnsmIHSHAXn",
    "EHnkwAYr ",
    "AEk ",
    "bEHl ",
    "bAEkspEYs ",
    "tAEb ",
    "lIHnIYfIYd ",
    "vERtIHkAXl tAEb ",
    "fAOrmfIYd ",
    "kAErAYj rIYtERn ",
    "SHIHft AWt ",
    "SHIHft IHn ",
    "dIHlIYt ",
    "dIHvIHs kAAntrAAl wAHn ",
    "dIHvIHs kAAntrAAl tUW ",
    "dIHvIHs kAAntrAAl THrIY ",
    "dIHvIHs kAAntrAAl fOWr ",
    "nAEk ",
    "sIHnk ",
    "EHnd tEHkst blAAk ",
    "kAEnsEHl ",
    "EHnd AXv mEHsIHj ",
    "sUWbstIHtUWt ",
    "EHskEYp ",
    "fAYEHld sIYpERAEtER ",
    "grUWp sIYpERAEtER ",
    "rIYkAOrd sIYpERAEtER ",
    "yUWnIHt sIYpERAEtER ",
    "spEYs ",
    "EHksklAEmEYSHAXn mAArk ",
    "dAHbl kwOWt ",
    "nUWmbER sAYn ",
    "dAAlER sAYn ",
    "pERsEHnt ",
    "AEmpERsAEnd ",
    "kwOWt ",
    "OWpEHn pEHrEHn ",
    "klOWz pEHrEHn ",
    "AEstEHrIHsk ",
    "plAHs ",
    "kAAmmAX ",
    "mIHnAHs ",
    "pIYrIYAAd ",
    "slAESH ",
    "zIHrOW ",
    "wAHn ",
    "tUW ",
    "THrIY ",
    "fOWr ",
    "fAYv ",
    "sIHks ",
    "sEHvAXn ",
    "EYt ",
    "nAYn ",
    "kAAlAXn ",
    "sEHmIHkAAlAXn ",
    "lEHs DHAEn ",
    "EHkwAXl sAYn ",
    "grEYtER DHAEn ",
    "kwEHsCHAXn mAArk ",
    "AEt sAYn ",
    "EY ",
    "bIY ",
    "sIY ",
    "dIY ",
    "IY ",
    "EHf ",
    "jIY  ",
    "EYtCH ",
    "AY ",
    "jEY ",
    "kEY ",
    "EHl ",
    "EHm ",
    "EHn ",
    "AA ",
    "pIY ",
    "kw ",
    "AAr ",
    "EHz ",
    "tIY ",
    "AHw ",
    "vIY ",
    "dAHblyUWw ",
    "EHks ",
    "wAYIY ",
    "zIY ",
    "lEHft brAEkEHt ",
    "bAEkslAESH ",
    "rAYt brAEkEHt ",
    "kAErEHt ",
    "AHndERskAOr ",
    "AEpAAstrAAfIH ",
    "EY ",
    "bIY ",
    "sIY ",
    "dIY ",
    "IY ",
    "EHf ",
    "jIY  ",
    "EYtCH ",
    "AY ",
    "jEY ",
    "kEY ",
    "EHl ",
    "EHm ",
    "EHn ",
    "AA ",
    "pIY ",
    "kw ",
    "AAr ",
    "EHz ",
    "tIY ",
    "AHw ",
    "vIY ",
    "dAHblyUWw ",
    "EHks ",
    "wAYIY ",
    "zIY ",
    "lEHft brEYs ",
    "vERtIHkAXl bAAr ",
    "rAYt brEYs ",
    "tAYld ",
    "dEHl ",
];
#[rustfmt::skip]
pub const ENG_SYM_TBL: [(&str, u8); 48] = [
    ("aa", 1), ("ae", 2), ("ah", 3), ("ao", 4), ("aw", 5), ("ax", 40),
    ("ay", 6), ("b", 7), ("ch", 8), ("d", 9), ("dh", 10), ("ea", 101),
    ("eh", 11), ("er", 12), ("ey", 13), ("f", 14), ("g", 15), ("h", 16),
    ("hh", 16), ("ia", 100), ("ih", 17), ("iy", 18), ("j", 19), ("jh", 19),
    ("k", 20), ("l", 21), ("m", 22), ("n", 23), ("ng", 24), ("oh", 4),
    ("ow", 25), ("oy", 26), ("p", 27), ("r", 28), ("s", 29), ("sh", 30),
    ("sil", 103), ("t", 31), ("th", 32), ("ua", 102), ("uh", 33), ("uw", 34),
    ("v", 35), ("w", 36), ("wh", 41), ("y", 37), ("z", 38), ("zh", 39),
];

#[rustfmt::skip]
pub const GSCH_ENGI_KOR_TBL: [&str; 26] = [
    "9i",
    "bi",
    "vi",
    "di",
    "i",
    "9p_",
    "jwu",
    "9cwu",
    "ai",
    "j9i",
    "k9i",
    "9L",
    "9M",
    "9N",
    "o",
    "pi",
    "kyu",
    "al_",
    "9v_",
    "ti",
    "yu",
    "b_i",
    "deb_Llyu",
    "9Gs_",
    "wai",
    "j9t_",
];
#[rustfmt::skip]
pub const GSCH_CARDINALS: [&str; 20] = [
    "zIHrOW ",
    "wAHn ",
    "tUW ",
    "THrIY ",
    "fOWr ",
    "fAYv ",
    "sIHks ",
    "sEHvAXn ",
    "EYt ",
    "nAYn ",
    "tEHn ",
    "IYlEHvAXn ",
    "twEHlv ",
    "THERtIYn ",
    "fOWrtIYn ",
    "fIHftIYn ",
    "sIHkstIYn ",
    "sEHvEHntIYn ",
    "EYtIYn ",
    "nAYntIYn ",
];
#[rustfmt::skip]
pub const GSCH_TWENTIES: [&str; 8] = [
    "twEHntIY ",
    "THERtIY ",
    "fAOrtIY ",
    "fIHftIY ",
    "sIHkstIY ",
    "sEHvEHntIY ",
    "EYtIY ",
    "nAYntIY ",
];
#[rustfmt::skip]
pub const GSCH_ORDINALS: [&str; 20] = [
    "zIHrOWEHTH ",
    "fERst ",
    "sEHkAHnd ",
    "THERd ",
    "fOWrTH ",
    "fIHfTH ",
    "sIHksTH ",
    "sEHvEHnTH ",
    "EYtTH ",
    "nAYnTH ",
    "tEHnTH ",
    "IYlEHvEHnTH ",
    "twEHlvTH ",
    "THERtIYnTH ",
    "fAOrtIYnTH ",
    "fIHftIYnTH ",
    "sIHkstIYnTH ",
    "sEHvEHntIYnTH ",
    "EYtIYnTH ",
    "nAYntIYnTH ",
];
#[rustfmt::skip]
pub const GSCH_ORD_TWENTIES: [&str; 8] = [
    "twEHntIYEHTH ",
    "THERtIYEHTH ",
    "fOWrtIYEHTH ",
    "fIHftIYEHTH ",
    "sIHkstIYEHTH ",
    "sEHvEHntIYEHTH ",
    "EYtIYEHTH ",
    "nAYntIYEHTH ",
];
